### ISSUE TITLE
ember-cli-scss-lint breaks PhantomJS

### ISSUE THREAD

**Issue by elwayman02** [tomasbasham/ember-cli-scss-lint#1]
This error only occurs when ember-cli-scss-lint is installed; PhantomJS works fine otherwise. I've reproduced this on multiple applications.

PhantomJS: 2.0
npm: 3.3.6
ember-cli: 1.13.8
ember-cli-scss-lint: 0.1.2

```
Building.Processing app.scss
Built project successfully. Stored in "/Users/jordan/Projects/app/tmp/class-tests_dist-UnCDGnCa.tmp".
not ok 1 PhantomJS 2.0 - global failure
    ---
        actual: >
            null
        message: >
            SyntaxError: Unexpected token 'const'
        Log: |
    ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by baileymiller182** [comment]
Same issue reproduced with: 

PhantomJS: 2.1.3
ember-cli: 1.13.7
ember-cli-scss-lint: 0.2.0
npm: 3.7.3
nodejs: 5.7.1
