### ISSUE TITLE
Excluding files

### ISSUE THREAD

**Issue by mscarchilli** [tomasbasham/ember-cli-scss-lint#7]
Is there a way to exclude files from being linted every time? It gets very annoying when you have many partials and vendor sass that you are using where you don't feel like reworking their code just so the lint doesn't output 50+ lines of errors.

**Comment by tomasbasham** [comment]
This addon should pass any options defined within `ember-cli-build.js` to the [ScssLinter](https://github.com/artursmirnov/broccoli-scss-lint) package this addon depend on. As far as I am aware the ScssLinter package should then pass these options to the scss_lint gem. So if you use the `--exclude` option you should be able to achieve what you want.

```
module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    scssLintOptions: {
      exclude: 'directory-or-files-to-exclude'
    }
  });

  /*
    This build file specifes the options for the dummy test app of this
    addon, located in `/tests/dummy`
    This build file does *not* influence how the addon or the app using it
    behave. You most likely want to be modifying `./index.js` or app's build file
  */

  return app.toTree();
};
```

The above may not be exact but play around with some of the options available [here](https://github.com/brigade/scss-lint#usage)

**Comment by mscarchilli** [comment]
So far no luck. I have tried this a few ways and it still linted the files. I feel like I'm missing something simple?
```
/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    outputPaths: {
      app: {
        css: {
          'app': '/assets/css/app.css',
        },
        js: '/assets/js/app.js'
      },
      vendor: {
        css: '/assets/css/vendor.css',
        js: '/assets/js/vendor.js'
      }
    },
    sassOptions: {
      extension: 'scss',
      file: './app/styles/app.scss',
      outputStyle: 'compressed',
      sourceMap: true,
      outFile: './dist/assets/css/app.css'
    },
    scssLintOptions: {
      exclude: './app/styles/partials'
    },
  });

  return app.toTree();
};
```

As well as adding into the .scss-lint.yml file as they say to do [here](https://github.com/brigade/scss-lint#configuration).
```
exclude: 'app/styles/partials/**'
```

**Comment by tomasbasham** [comment]
Ok so the problem to me looks like one where the path you are providing is not actually the path to the SCSS files referenced by the broccoli pipeline. So whilst those files may be in your codebase when broccoli is doing its thing it copies temporary files to a path similar to `tmp/scss_linter-input_base_path-TfCSYJ5d.tmp/0/`. This is where you want to point the exclude path toward. Of course I don't expect you to put this in the config file, especially since it changes each run of broccoli. I will either try to append this path to the appropriate options (if supplied) or bring in @artursmirnov to help with this.

**Comment by mscarchilli** [comment]
Just today I realized that tmp directory is causing major issues within my editor as well. The file size of that directory has gotten up to 10GB on me which kept crashing my editor. 

So looks like I'm going to have to ditch the framework completely in favor of another that doesn't use broccoli. I just wish broccoli wasn't so deeply embedded into the framework so the task runner could easily be switched over to Grunt or Gulp, which I prefer over broccoli significantly. Don't have the time to convert everything over to Grunt. Back to the drawing board. Thanks for the help though.

**Comment by tomasbasham** [comment]
Glad to help. I'll keep this issue open as it is something that could definitely be improved
