### ISSUE TITLE
Support linting of stylesheets outside of app/styles directory

### ISSUE THREAD

**Issue by wireframe** [tomasbasham/ember-cli-scss-lint#9]
As a user of the excellent ember-component-css addon, 90% of my stylesheets live in app/pods/components/foo-component/styles.scss which is currently not linted by the ember-cli-scss-lint addon.

Is it possible to either detect additional scss files or pass in a configuration option to include additional files for linting?

**Comment by tomasbasham** [comment]
I'm currently working on excluding directories as part of the addon configuration. So I should be able to include and `includePaths` option to do what you need here.

**Comment by tomasbasham** [comment]
Ideally I would like this addon to work with the pods structure. I have never used pods for any of my own ember projects so it never was a priority. I'll look into it
